[cogs]
# Cog file(s)
# full path from root dir or bot without suffix
# ex: cog_files/sample
file = []
# Cog folder(s)
# full path from root dir of bot, suffix "/" if optional
# ex: cog_folders/sample/
folder = [
	"lrb_background",
	"lrb_command"
]

[database]
	[database.stable]
	# Type, valid values: mongodb
	type = "mongodb"
	# Host uri
	url = ""
	# Port to use if needed
	port = ""

	[database.dev]
	# Type, valid values: mongodb
	type = "mongodb"
	# Host uri
	url = ""
	# Port to use if needed
	port = ""

[intent]
# Intent base, valid values: all, default, none
base = "default"

	[intent.items]
	# Intent item, valid keys: bans, dm_messages, dm_reactions, dm_typing, emojis, emojis_and_stickers, guild_messages, guild_reactions, guild_scheduled_events, guild_typing, guilds, integrations, invites, members, messages, presences, reactions, typing, value, voice_states, webhooks
	# Value should be boolen(true or false)
	# Example:
	# dm_messages = true
	# This will override some of the base settings

[prefix]
# Prefix type, valid values: string, array, function
# string: for SINGLE prefix
# array: for MULTI prefix
# function: other, ex: server custom prefix
type = "function"

# prefix: when prefix type is string, use this setting
#  when prefix type is "function", use this setting as default prefix
# prefixes: when prefix type is "array", use this setting
# function_path: when prefix type is "function", use this setting,
#  full import path with function name from root dir of bot
	[prefix.stable]
	prefix = ""
	prefixes = []
	function_path = ""
	
	[prefix.dev]
	prefix = ""
	prefixes = []
	function_path = "core.prefix.get_prefix"

[tokens]
# Bot token to use in all mode, will overwrite other token setting
all = ""
# Bot token to use in stable mode
stable = ""
# Bot token to use in dev mode
dev = ""

[misc]
# Owner(s) ID
owner_ids = []

[server]
# Default language when join a new server
default_lang_code = "en"
